version: "3"

services:
  portainer:
    image: portainer/portainer
    command: "-H unix:///var/run/docker.sock"
    networks:
      - traefik-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]  
      labels:
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:lam-812.lampiris.local"
        - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    external:
      name: traefik_traefik-net