- name: "Wait Docker is started"
  service:
    name: docker
    state: started

- name: "Is in Swarm mode"
  command: 'docker node ls'
  register: "swarm_mode_result"
  ignore_errors: true

- name: Enable Swarm Mode
  shell: 'docker swarm init --advertise-addr="{{ansible_default_ipv4.address}}"'
  when: "swarm_mode_result.rc == 1"