test:
  tags:
    - vagrant
  script:
    - cd debian-box && vagrant up --provision
    - docker -H tcp://${SWARM_HOST}:2375 node ls 
    - docker -H tcp://${SWARM_HOST}:2375 service ls | grep portainer || { echo "portainer service should be available"; false; }
    - vagrant destroy -f