- name: "Is Portainer running"
  command: 'docker service ps portainer'
  register: "portainer_status"
  ignore_errors: true
  
- name: Start Portainer
  shell: docker service create \
    --name portainer \
    --publish 9000:9000 \
    --constraint 'node.role == manager' \
    --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock \
    portainer/portainer \
    -H unix:///var/run/docker.sock
  when: "portainer_status.rc == 1"
