- name: "Copy Portainer Docker stack file"
  copy:
    src: "{{ role_path }}/files/docker-stack.yml"
    dest: "/tmp/portainer-docker-stack.yml"

- name: "Is Portainer running"
  command: 'docker service ps portainer'
  register: "portainer_status"
  ignore_errors: true

- name: "Start Portainer service"
  command: "docker stack deploy --compose-file /tmp/portainer-docker-stack.yml portainer"
  when: "portainer_status.rc == 1"
